version: '3.8'

services:
  accueil:
    build: ./accueil
    ports:
      - "8000:80"

  kiacook:
    build: ./kiacook
    ports:
      - "8082:80"

  frontend:
    build: ./frontend
    ports:
      - "8083:80"

  firstappnext:
    build: ./firstappnext
    ports:
      - "8080:3000"

  rocket-ecommerce-v1.0.7:
    build: ./rocket-ecommerce-v1.0.7
    ports:
      - "8084:5005"
    environment:

